Documentation for the scripting feature of auto responses
lucascphillips/aut-bot-app pull request #111
Opened 2021-01-31 23:39 UTC by jammiess

Adds documentation for how users can make the most of the auto response scripting feature.

2021-01-31 23:49 UTC, jammiess commented
add documentation for the shorthand versions of the global variables

2021-02-01 00:08 UTC, johnyburd commented on docs/content/features/auto-responses/index.md
> +#### Struct
I think structs are too low-level for this type of documentation

2021-02-01 00:08 UTC, johnyburd commented on docs/content/features/auto-responses/index.md
> +The `sum` function will sum all of the elements of an iterable. It accepts a single parameter that is the iterable value to sum over. `sum` requires that the parameter passed in is solely composed of
this is too detailed.  no one who knows what an iterator is doesn't already know what sum does, and it's unlikely anyone cares about the type output

2021-02-01 00:08 UTC, johnyburd commented on docs/content/features/auto-responses/index.md
> +## Starlark
Change heading to `Eval`

2021-02-01 00:08 UTC, johnyburd commented on docs/content/features/auto-responses/index.md
> +![eval](./eval_demo.png)
I think maybe the first demo should be simpler (since regexes haven't even been introduced yet)

2021-02-01 00:08 UTC, johnyburd commented on docs/content/features/auto-responses/index.md
> +#### \[e script\]
change to `[eval script]` and then mention elsewhere that `e` is an alias

2021-02-01 00:08 UTC, johnyburd commented on docs/content/features/auto-responses/index.md
> +`message` is a struct with members:
make these tables

2021-02-01 00:08 UTC, johnyburd commented on docs/package.json
> +    "start": "gatsby develop --open",
remove this before merge

2021-02-01 00:08 UTC, johnyburd commented on docs/content/features/auto-responses/index.md
>  The auto response settings pane can be accessed by the `settings responses` command
also add:
Allow Embeds, bool, If false, architus will escape links in responses so discord won't embed them
Allow Newlines, bool, Whether newlines will be stripped or allowed in auto response outputs

2021-02-01 01:11 UTC, johnyburd commented on docs/content/features/auto-responses/index.md
> +assert(sum(values) == 10)
also, if what you said is true, wouldn't this be false

2021-02-02 01:38 UTC, johnyburd requested changes

2021-02-02 01:38 UTC, johnyburd commented on docs/content/features/auto-responses/index.md
> +See [here](/features/auto-responses/#starlark) for more information on what can go into a script and how to write them.
this is broken now

2021-02-02 01:38 UTC, johnyburd commented on docs/content/features/auto-responses/index.md
> +`message` struct (refers to triggering message):
make these `######`s so the merge with the tables nicely

2021-02-02 01:38 UTC, johnyburd commented on docs/content/features/auto-responses/index.md
> +Starlark has some peculiarities about it that make it more difficult to use when coming from Python. One such peculiarity is that strings are not iterable in Starlark, only lists. To iterate over a s
this might look good in one of the info blocks, but idk

2021-02-19 05:44 UTC, merged